### ISSUE TITLE
intent aliasing absent while training/testing the model

### ISSUE THREAD

**Issue by nvinayvarma189** [skit-ai/dialogy-template-simple-transformers#52]
I ran this for a project

```
slu train --lang id --version 0.1.1
```

I have mentioned the intent aliases in the config.yaml in this way:

```yaml
tasks:
  classification:
    alias:
      new_intent_1: _oos_
      new_intent_2: _oos_
      new_intent_3: _oos_
```

After we are reading the training file [here](https://github.com/skit-ai/dialogy-template-simple-transformers/blob/main/slu/slu/dev/train.py#L204), we are not mapping the aliases present in `config.yaml`. 

**Possible Solution:**

We do have a function `read_multiclass_dataset_csv` in `csv.py` which does this but it is not used anywhere in the project.
